use serde::Serialize;

use crate::error::Result;
use crate::session::CdpSession;

// --- Param types ---

/// Parameters for [`InputCommands::input_dispatch_mouse_event`].
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchMouseEventParams {
    /// Event type: `"mousePressed"`, `"mouseReleased"`, `"mouseMoved"`, `"mouseWheel"`.
    #[serde(rename = "type")]
    pub event_type: String,
    /// X coordinate relative to the viewport (CSS pixels).
    pub x: f64,
    /// Y coordinate relative to the viewport (CSS pixels).
    pub y: f64,
    /// Mouse button: `"none"`, `"left"`, `"middle"`, `"right"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub button: Option<String>,
    /// Number of times the mouse button was clicked (default: 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i32>,
}

/// A single touch point for [`DispatchTouchEventParams`].
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TouchPoint {
    /// X coordinate relative to the viewport (CSS pixels).
    pub x: f64,
    /// Y coordinate relative to the viewport (CSS pixels).
    pub y: f64,
}

/// Parameters for [`InputCommands::input_dispatch_touch_event`].
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchTouchEventParams {
    /// Event type: `"touchStart"`, `"touchEnd"`, `"touchMove"`, `"touchCancel"`.
    #[serde(rename = "type")]
    pub event_type: String,
    /// Active touch points. For `touchEnd`, this should be empty.
    pub touch_points: Vec<TouchPoint>,
}

/// Parameters for [`InputCommands::input_dispatch_key_event`].
#[derive(Debug, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchKeyEventParams {
    /// Event type: `"keyDown"`, `"keyUp"`, `"rawKeyDown"`, `"char"`.
    #[serde(rename = "type")]
    pub event_type: String,
    /// Key value as defined in the UI Events spec (e.g. `"Enter"`, `"a"`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Text generated by this keystroke. For printable characters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Unmodified text generated by this keystroke.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unmodified_text: Option<String>,
    /// DOM `KeyboardEvent.code` (e.g. `"KeyA"`, `"Enter"`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Windows virtual key code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub windows_virtual_key_code: Option<i32>,
    /// Native virtual key code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_virtual_key_code: Option<i32>,
    /// Bit field for modifier keys: Alt=1, Ctrl=2, Meta/Cmd=4, Shift=8.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<i32>,
}

// --- Domain trait ---

/// `Input` domain CDP methods.
///
/// These generate `isTrusted: true` events because they are injected
/// at the browser process level, not via JavaScript.
///
/// Reference: <https://chromedevtools.github.io/devtools-protocol/tot/Input/>
pub trait InputCommands {
    /// Dispatches a mouse event to the page.
    ///
    /// Events dispatched via CDP Input domain are treated as real user input
    /// by the browser (`isTrusted: true`).
    ///
    /// CDP: `Input.dispatchMouseEvent`
    async fn input_dispatch_mouse_event(&self, params: &DispatchMouseEventParams) -> Result<()>;

    /// Dispatches a key event to the page.
    ///
    /// Events dispatched via CDP Input domain produce `isTrusted: true`
    /// keyboard events, including typing indicators in web apps.
    ///
    /// CDP: `Input.dispatchKeyEvent`
    async fn input_dispatch_key_event(&self, params: &DispatchKeyEventParams) -> Result<()>;

    /// Dispatches a touch event to the page.
    ///
    /// CDP: `Input.dispatchTouchEvent`
    async fn input_dispatch_touch_event(&self, params: &DispatchTouchEventParams) -> Result<()>;
}

impl InputCommands for CdpSession {
    async fn input_dispatch_mouse_event(&self, params: &DispatchMouseEventParams) -> Result<()> {
        self.call_no_response("Input.dispatchMouseEvent", params)
            .await
    }

    async fn input_dispatch_key_event(&self, params: &DispatchKeyEventParams) -> Result<()> {
        self.call_no_response("Input.dispatchKeyEvent", params)
            .await
    }

    async fn input_dispatch_touch_event(&self, params: &DispatchTouchEventParams) -> Result<()> {
        self.call_no_response("Input.dispatchTouchEvent", params)
            .await
    }
}
