provider_type = "ollama"
base_url = "http://pc:11434"

[[model_overrides]]
model = "gemma4:26b-a4b-it-qat"
context_window_tokens_override = 16384

[[model_overrides]]
model = "gemma4:31b-it-qat"
context_window_tokens_override = 16384

[[model_overrides]]
model = "gemma4:12b-it-qat"
context_window_tokens_override = 16384

[[model_overrides]]
model = "gemma4:e2b-it-qat"
context_window_tokens_override = 16384

[[model_overrides]]
model = "gemma4:e4b-it-qat"
context_window_tokens_override = 16384

[[model_overrides]]
model = "qwen3.5:0.8b-q8_0"
context_window_tokens_override = 16384

[[model_overrides]]
model = "qwen3.5:2b-q8_0"
context_window_tokens_override = 16384

[[model_overrides]]
model = "qwen3.5:4b-q4_K_M"
context_window_tokens_override = 16384

[[model_overrides]]
model = "qwen3.5:9b-q4_K_M"
context_window_tokens_override = 16384

[[model_overrides]]
model = "qwen3-embedding:4b-q4_K_M"
context_window_tokens_override = 4096
